# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Webtop
version: 1e39c8db-ls180
slug: webtop
description: Full Debian XCFE desktop environment accessible via any modern web browser
url: https://github.com/felipecrs/webtop-hass-addons
arch:
  - amd64
init: false
ingress: true
ingress_port: 3000
ingress_stream: true
panel_icon: mdi:remote-desktop
video: true
docker_api: true
backup: cold
map:
  - type: addon_config
    path: /config
    read_only: false
  - type: media
    path: /media
    read_only: false
ports:
  3001/tcp: null
